"""one health webhook

Revision ID: 677c2f383d70
Revises: 812b0bc3af4c
Create Date: 2026-10-01 22:24:22.221114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677c2f383d70'
down_revision: Union[str, Sequence[str], None] = '812b0bc3af4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('one_health_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('one_health_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'one_health_attempts')
    op.drop_column('alerts', 'one_health_notified_at')
    # ### end Alembic commands ###
