"""alert acknowledgement

Revision ID: 812b0bc3af4c
Revises: 878fea69580f
Create Date: 2026-09-30 08:48:26.835145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812b0bc3af4c'
down_revision: Union[str, Sequence[str], None] = '878fea69580f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.UUID(), nullable=True))
    op.create_foreign_key('alerts_acknowledged_by_fkey', 'alerts', 'users', ['acknowledged_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('alerts_acknowledged_by_fkey', 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'acknowledged_at')
    # ### end Alembic commands ###
