"""initial schema

Revision ID: 878fea69580f
Revises: 
Create Date: 2026-09-29 17:24:35.405034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878fea69580f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('districts',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_districts_boundary', 'districts', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_districts_centroid', 'districts', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('weather_cache',
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('humidity_mean', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('blocks',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_blocks_boundary', 'blocks', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_blocks_centroid', 'blocks', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_geospatial_table('alerts',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('syndrome', sa.String(length=48), nullable=True),
    sa.Column('disease', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('area', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('case_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_alerts_area', 'alerts', ['area'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_alerts_center', 'alerts', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('risk_scores',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('disease', sa.String(length=32), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_block_id'), 'risk_scores', ['block_id'], unique=False)
    op.create_geospatial_table('villages',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_villages_boundary', 'villages', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_villages_centroid', 'villages', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_villages_block_id'), 'villages', ['block_id'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_geospatial_table('advisories',
    sa.Column('template_id', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('rendered_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_center', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('disease', sa.String(length=32), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_advisories_target_center', 'advisories', ['target_center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('herds',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_herds_location', 'herds', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_herds_owner_user_id'), 'herds', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_herds_village_id'), 'herds', ['village_id'], unique=False)
    op.create_table('advisory_recipients',
    sa.Column('advisory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_recipients_advisory_id'), 'advisory_recipients', ['advisory_id'], unique=False)
    op.create_index(op.f('ix_advisory_recipients_user_id'), 'advisory_recipients', ['user_id'], unique=False)
    op.create_table('animals',
    sa.Column('ear_tag', sa.String(length=12), nullable=True),
    sa.Column('herd_id', sa.UUID(), nullable=False),
    sa.Column('species', sa.String(length=16), nullable=False),
    sa.Column('breed', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ear_tag')
    )
    op.create_index(op.f('ix_animals_herd_id'), 'animals', ['herd_id'], unique=False)
    op.create_geospatial_table('reports',
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('herd_id', sa.UUID(), nullable=True),
    sa.Column('animal_id', sa.UUID(), nullable=True),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('species', sa.String(length=16), nullable=False),
    sa.Column('symptoms', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('sick_count', sa.Integer(), nullable=False),
    sa.Column('dead_count', sa.Integer(), nullable=False),
    sa.Column('total_at_risk', sa.Integer(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('voice_transcript', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('device_triage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_on_device_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_geospatial_index('idx_reports_location', 'reports', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_reports_created_on_device_at'), 'reports', ['created_on_device_at'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_village_id'), 'reports', ['village_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('animal_id', sa.UUID(), nullable=True),
    sa.Column('herd_id', sa.UUID(), nullable=True),
    sa.Column('vaccine', sa.String(length=32), nullable=False),
    sa.Column('given_on', sa.Date(), nullable=False),
    sa.Column('next_due_on', sa.Date(), nullable=True),
    sa.Column('given_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_animal_id'), 'vaccinations', ['animal_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_herd_id'), 'vaccinations', ['herd_id'], unique=False)
    op.create_geospatial_table('cases',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('suspected_disease', sa.String(length=32), nullable=True),
    sa.Column('confirmed_disease', sa.String(length=32), nullable=True),
    sa.Column('assigned_vet_id', sa.UUID(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('herd_id', sa.UUID(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vet_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_cases_location', 'cases', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_cases_block_id'), 'cases', ['block_id'], unique=False)
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_suspected_disease'), 'cases', ['suspected_disease'], unique=False)
    op.create_table('triage_results',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_syndrome', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('zoonotic_flag', sa.Boolean(), nullable=False),
    sa.Column('unknown_syndrome', sa.Boolean(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triage_mismatch', sa.Boolean(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_primary_syndrome'), 'triage_results', ['primary_syndrome'], unique=False)
    op.create_index(op.f('ix_triage_results_report_id'), 'triage_results', ['report_id'], unique=False)
    op.create_table('case_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('case_reports',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_case_reports_case_id'), 'case_reports', ['case_id'], unique=False)
    op.create_table('lab_samples',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('qr_code', sa.String(length=16), nullable=False),
    sa.Column('sample_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('result_disease', sa.String(length=32), nullable=True),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_lab_samples_case_id'), 'lab_samples', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_samples_case_id'), table_name='lab_samples')
    op.drop_table('lab_samples')
    op.drop_index(op.f('ix_case_reports_case_id'), table_name='case_reports')
    op.drop_table('case_reports')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_triage_results_report_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_primary_syndrome'), table_name='triage_results')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_cases_suspected_disease'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.drop_index(op.f('ix_cases_block_id'), table_name='cases')
    op.drop_geospatial_index('idx_cases_location', table_name='cases', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('cases')
    op.drop_index(op.f('ix_vaccinations_herd_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_animal_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_reports_village_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_on_device_at'), table_name='reports')
    op.drop_geospatial_index('idx_reports_location', table_name='reports', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('reports')
    op.drop_index(op.f('ix_animals_herd_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_advisory_recipients_user_id'), table_name='advisory_recipients')
    op.drop_index(op.f('ix_advisory_recipients_advisory_id'), table_name='advisory_recipients')
    op.drop_table('advisory_recipients')
    op.drop_index(op.f('ix_herds_village_id'), table_name='herds')
    op.drop_index(op.f('ix_herds_owner_user_id'), table_name='herds')
    op.drop_geospatial_index('idx_herds_location', table_name='herds', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('herds')
    op.drop_geospatial_index('idx_advisories_target_center', table_name='advisories', postgresql_using='gist', column_name='target_center')
    op.drop_geospatial_table('advisories')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_villages_block_id'), table_name='villages')
    op.drop_geospatial_index('idx_villages_centroid', table_name='villages', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_index('idx_villages_boundary', table_name='villages', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('villages')
    op.drop_index(op.f('ix_risk_scores_block_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_geospatial_index('idx_alerts_center', table_name='alerts', postgresql_using='gist', column_name='center')
    op.drop_geospatial_index('idx_alerts_area', table_name='alerts', postgresql_using='gist', column_name='area')
    op.drop_geospatial_table('alerts')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_geospatial_index('idx_blocks_centroid', table_name='blocks', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_index('idx_blocks_boundary', table_name='blocks', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('blocks')
    op.drop_table('weather_cache')
    op.drop_geospatial_index('idx_districts_centroid', table_name='districts', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_index('idx_districts_boundary', table_name='districts', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('districts')
    # ### end Alembic commands ###
